import sympy as sp
from sympy import ccode
import re

# NB! Note that PX4 normalizes forces and moments.
# They do not represent physical units.
# Roll/pitch, Yaw, Thrust have different scales, and cannot be directly compared.

# Normalized mixer M. This is equivalent to the PX4 octacopter mixer.
# The mixer matrix converts a generalized wrench command, v, to motor commands, u.
# In PX4 it is generated by taking the Moore-Penrose pseudoinverse of the
# actuator effectiveness matrix
s = 1/sp.sqrt(2)
M = sp.Matrix([
    [-s,  s,  1, -1],
    [ s,  s, -1, -1],
    [ s, -s,  1, -1],
    [-s, -s, -1, -1],
    [ s,  s,  1, -1],
    [-s,  s, -1, -1],
    [-s, -s,  1, -1],
    [ s, -s, -1, -1],
])

# We assume lower motors produce less thrust and torque than the top ones due to turbulent air
# The exact constant is a tuning parameter.
l_T = sp.Rational("0.6")  # thrust
l_Y = sp.Rational("0.6")  # yaw
A_nom = sp.Matrix([
    [-1,  1,  1, -1,  l_T, -l_T, -l_T,  l_T],
    [ 1,  1, -1, -1,  l_T,  l_T, -l_T, -l_T],
    [ 1, -1,  1, -1,  l_Y, -l_Y,  l_Y, -l_Y],
    [-1, -1, -1, -1, -l_T, -l_T, -l_T, -l_T],
])
# Generalized wrench command: roll, pitch, yaw, z-thrust.
R, P, Y, Z = sp.symbols("R P Y Z")
v_nom = sp.Matrix([R, P, Y, Z])

# Nominal forces
u_nom = M * v_nom
f_nom = A_nom * u_nom

# A_f_upper: Failed upper motor (M3)
A_f_upper = A_nom.copy()
A_f_upper[:, 2] = 0 * A_f_upper[:, 2]  # Complete failure
A_f_upper[:, 5] = sp.Matrix([-1,  1, -1, -1])  # No longer has top propeller creating turbulence

# A_f_lower: Failed lower rotor (M8)
A_f_lower = A_nom.copy()
A_f_lower[:, 7] = 0 * A_f_lower[:, 7]  # Complete failure

# Solve: A_mod M v_mod = A_nom M v
# This is the [rpyz] command px4 would have to use with the mixer
# in order to achieve the same moments when there is a failed motor
# (We assume that the PID controller can reach this equilibrium)
v_f_upper = (A_f_upper * M).LUsolve((A_nom * M) * v_nom)
v_f_lower = (A_f_lower * M).LUsolve((A_nom * M) * v_nom)
u_f_upper = M * v_f_upper
u_f_lower = M * v_f_lower

sp.pprint(sp.simplify(v_f_lower.subs({R: 0, P: -0.1, Y: 0, Z: -0.45})).evalf())
sp.pprint(sp.simplify(v_f_upper.subs({R: 0, P: -0.1, Y: 0, Z: -0.45})).evalf())

# Verify that correct forces are allocated
assert A_f_upper * u_f_upper == f_nom
assert A_f_lower * u_f_lower == f_nom

ratio = u_f_lower.multiply_elementwise(u_nom.applyfunc(lambda x: 1/x))
sp.pprint(v_f_upper.evalf())


## Code generation

def to_px4_code(code: str) -> str:
    """Convert SymPy C code to PX4 float style."""

    code = code.replace("M_SQRT2", "M_SQRT2_F")

    # Add `f` suffix to all decimal literals, including in fractions.
    def add_suffix(m):
        num = m.group(0)
        return num + "f"

    code = re.sub(r"\b\d+\.\d+\b", add_suffix, code)

    return code


u_expr = sp.simplify(u_f_lower)  # 8×1
print("LOWER MOTOR FAILED CASE:")
print(f"const float worst_motor_bomi = {to_px4_code(ccode(u_f_lower[7].evalf()))};")

print("UPPER MOTOR FAILED CASE:")
print(f"const float worst_motor_bomi = {to_px4_code(ccode(u_f_upper[5].evalf()))};")

print("\nFull expressions for all motors (lower motor failed):")
for i in range(8):
    print(f"Motor {i+1}: {to_px4_code(ccode(u_expr[i].evalf()))};")

print("\nFull expressions for all motors (upper motor failed):")
u_expr = sp.simplify(u_f_upper)  # 8×1
for i in range(8):
    print(f"Motor {i+1}: {to_px4_code(ccode(u_expr[i].evalf()))};")
