#!/bin/sh
#
# @name Aviant ATS
#
# @type Other
# @class Other
#

param set-default MAV_TYPE 0

param set-default COM_RC_IN_MODE 1  # Joystick only (stops QGC complaining about setup)

param set-default SENS_BOARD_ROT 22  # 270 roll, 90 yaw

param set-default SER_TEL2_BAUD 921600
param set-default MAV_0_CONFIG 102
param set-default MAV_0_MODE 15  # ATS
param set-default MAV_0_FORWARD 1
param set-default MAV_0_RATE 0
param set-default MAV_0_RADIO_CTL 0
param set-default MAV_0_FLOW_CTRL 0

param set-default SER_TEL1_BAUD 230400
param set-default MAV_1_CONFIG 101
param set-default MAV_1_MODE 13  # Parachute
param set-default MAV_1_FORWARD 1
param set-default MAV_1_RATE 0
param set-default MAV_1_RADIO_CTL 0
param set-default MAV_1_FLOW_CTRL 0
